/*
 * art-frame -- an artful sands image emulation
 *
 * Copyright (C) 2019 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/art-frame>
 *
 * Author's web site: www.juergen-reuter.de
 */

#include <audio-control.hh>
#include <log.hh>
#include <titled-dial.hh>

Audio_control::Audio_control(QWidget *parent, const IConfig *config)
  : QGroupBox(tr("Audio"), parent)
{
  QBoxLayout *layout = new QHBoxLayout();
  if (!layout) {
    Log::fatal("Audio_control::Audio_control(): not enough memory");
  }
  setLayout(layout);

  QWidget *volume_control = create_volume_control(&_dial_volume, config);
  layout->addWidget(volume_control);

  _button_mute_unmute = new Titled_button(this, "mute / unmute");
  layout->addWidget(_button_mute_unmute);

  _image_mute = new QImage("unmuted.png");
  if (!_image_mute) {
    Log::fatal("Audio_control::Audio_control(): not enough memory");
  }

  _image_unmute = new QImage("muted.png");
  if (!_image_unmute) {
    Log::fatal("Audio_control::Audio_control(): not enough memory");
  }
}

Audio_control::~Audio_control()
{
  // Q objects will be deleted by Qt, just set them to 0
  _dial_volume = 0;
  _button_mute_unmute = 0;
  _image_mute = 0;
  _image_unmute = 0;
}

QDial *
Audio_control::get_dial_volume() const
{
  return _dial_volume;
}

Titled_button *
Audio_control::get_button_mute_unmute() const
{
  return _button_mute_unmute;
}

QImage *
Audio_control::get_image_mute() const
{
  return _image_mute;
}

QImage *
Audio_control::get_image_unmute() const
{
  return _image_unmute;
}

QWidget *
Audio_control::create_volume_control(QDial **dial_volume,
                                     const IConfig *config)
{
  QWidget *volume_control = new QWidget();
  if (!volume_control) {
    Log::fatal("Audio_control::create_volume_control(): not enough memory");
  }

  QVBoxLayout *layout = new QVBoxLayout();
  if (!layout) {
    Log::fatal("Audio_control::create_volume_control(): not enough memory");
  }
  volume_control->setLayout(layout);

  const double initial_volume = config->get_audio_initial_volume();
  *dial_volume = new Titled_dial(volume_control);
  if (!(*dial_volume)) {
    Log::fatal("Audio_control::create_volume_control(): not enough memory");
  }
  (*dial_volume)->setToolTip(tr("Volume"));
  (*dial_volume)->setValue((int)(initial_volume * (*dial_volume)->maximum()));
  layout->addWidget(*dial_volume);

  QFont font("Arial", IConfig::TITLE_FONT_SIZE, QFont::Normal);
  font.setCapitalization(QFont::AllUppercase);
  QLabel *label = new QLabel(tr("Volume"), volume_control);
  if (!label) {
    Log::fatal("Audio_control::create_volume_control(): not enough memory");
  }
  label->setFont(font);
  label->setAlignment(Qt::AlignHCenter);
  layout->addWidget(label);

  return volume_control;
}

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
