/*
 * art-frame -- an artful sands image emulation
 *
 * Copyright (C) 2019 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/art-frame>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef AUDIO_CONTROL_HH
#define AUDIO_CONTROL_HH

#include <QtWidgets/QDial>
#include <QtWidgets/QGroupBox>
#include <iconfig.hh>
#include <titled-button.hh>

class Audio_control : public QGroupBox
{
  Q_OBJECT
public:
  explicit Audio_control(QWidget *parent, const IConfig *config);
  virtual ~Audio_control();
  QDial *get_dial_volume() const;
  Titled_button *get_button_mute_unmute() const;
  QImage *get_image_mute() const;
  QImage *get_image_unmute() const;
private:
  QDial *_dial_volume;
  Titled_button *_button_mute_unmute;
  QImage *_image_mute;
  QImage *_image_unmute;
  QWidget *create_volume_control(QDial **dial_volume, const IConfig *config);
};

#endif /* AUDIO_CONTROL_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
