/*
 * art-frame -- an artful sands image emulation
 *
 * Copyright (C) 2016, 2019 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/art-frame>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef CONFIG_READER_HH
#define CONFIG_READER_HH

#include <xercesc/dom/DOM.hpp>
#include <abstract-config-reader.hh>
#include <config.hh>

class Config_reader : public Abstract_config_reader
{
public:
  Config_reader(Config *config);
  virtual ~Config_reader();
protected:
  virtual void parse_document(const xercesc::DOMElement *elem_config);
  virtual void print_config() const;
private:
  Config *_config;
  void parse_power_save(const xercesc::DOMElement *elem_power_save);
  void parse_kiosk_mode(const xercesc::DOMElement *ekem_kiosk_mode);
  void parse_images(const xercesc::DOMElement *elem_config);
  const Config_image *parse_image(const xercesc::DOMElement *elem_image);
  const Config_image *parse_from_file(const xercesc::DOMElement *elem_from_file);
  const XMLCh *parse_path(const xercesc::DOMElement *elem_path);
};

#endif /* CONFIG_READER_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
