/*
 * art-frame -- an artful sands image emulation
 *
 * Copyright (C) 2016, 2019 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/art-frame>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef DIAL_CONTROL_HH
#define DIAL_CONTROL_HH

#include <QtWidgets/QGroupBox>
#include <QtWidgets/QDial>

class Dial_control : public QGroupBox
{
  Q_OBJECT
public:
  explicit Dial_control(QWidget *parent,
                        const char *label,
                        const double initial_value,
                        const char *tool_tip);
  virtual ~Dial_control();
  int minimum() const;
  int maximum() const;
  void set_value(const int value);
  int value() const;
//public slots:
//  void slot_value_changed(const int value);
signals:
  void value_changed(const int value);
private:
  QDial *_dial;
};

#endif /* DIAL_CONTROL_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
