/*
 * art-frame -- an artful sands image emulation
 *
 * Copyright (C) 2019 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/art-frame>
 *
 * Author's web site: www.juergen-reuter.de
 */

#include <global-control.hh>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <log.hh>
#include <titled-button.hh>

Global_control::Global_control(QWidget *parent, const IConfig *config)
  : QGroupBox(tr("Art Frame"), parent)
{
  QBoxLayout *layout = new QHBoxLayout();
  if (!layout) {
    Log::fatal("Global_control::Global_control(): not enough memory");
  }
  setLayout(layout);

  if (config->get_enable_button_quit()) {
    _button_quit =
      new Titled_button(this, "shut down system", "Quit", "quit.png");
    layout->addWidget(_button_quit);
  } else {
    _button_quit = 0;
  }

  _button_about =
    new Titled_button(this, "about this application", "About", "about.png");
  layout->addWidget(_button_about);

  _button_license =
    new Titled_button(this, "show license", "License", "license.png");
  layout->addWidget(_button_license);
}

Global_control::~Global_control()
{
  // Q objects will be deleted by Qt, just set them to 0
  _button_quit = 0;
  _button_about = 0;
  _button_license = 0;
}

QAbstractButton *
Global_control::get_button_quit() const
{
  return _button_quit;
}

QAbstractButton *
Global_control::get_button_about() const
{
  return _button_about;
}

QAbstractButton *
Global_control::get_button_license() const
{
  return _button_license;
}

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
