/*
 * art-frame -- an artful sands image emulation
 *
 * Copyright (C) 2019 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/art-frame>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef IMAGE_CONTROL_HH
#define IMAGE_CONTROL_HH

#include <QtWidgets/QDial>
#include <QtWidgets/QAbstractButton>
#include <QtWidgets/QGroupBox>

class Image_control : public QGroupBox
{
  Q_OBJECT
public:
  explicit Image_control(QWidget *parent);
  virtual ~Image_control();
  QAbstractButton *get_button_previous() const;
  QAbstractButton *get_button_reset() const;
  QAbstractButton *get_button_next() const;
private:
  QAbstractButton *_button_previous;
  QAbstractButton *_button_reset;
  QAbstractButton *_button_next;
  QWidget *create_volume_control(QDial **dial_volume);
};

#endif /* IMAGE_CONTROL_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
