/*
 * art-frame -- an artful sands image emulation
 *
 * Copyright (C) 2019 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/art-frame>
 *
 * Author's web site: www.juergen-reuter.de
 */

#include <image-control.hh>
#include <QtWidgets/QLabel>
#include <log.hh>
#include <qt-utils.hh>

Image_control::Image_control(QWidget *parent)
  : QGroupBox(tr("Image"), parent)
{
  QBoxLayout *layout = new QHBoxLayout();
  if (!layout) {
    Log::fatal("Image_control::Image_control(): not enough memory");
  }
  setLayout(layout);

  Qt_utils::create_button(this,
                          &_button_previous, "reset to previous image",
                          &_pixmap_previous, "previous.png", &_icon_previous);
  layout->addWidget(_button_previous);

  Qt_utils::create_button(this,
                          &_button_reset, "reset current image",
                          &_pixmap_reset, "reset.png", &_icon_reset);
  layout->addWidget(_button_reset);

  Qt_utils::create_button(this,
                          &_button_next, "reset to next image",
                          &_pixmap_next, "next.png", &_icon_next);
  layout->addWidget(_button_next);
}

Image_control::~Image_control()
{
  // Q objects will be deleted by Qt, just set them to 0
  _button_previous = 0;
  _icon_previous = 0;
  _pixmap_previous = 0;
  _button_reset = 0;
  _icon_reset = 0;
  _pixmap_reset = 0;
  _button_next = 0;
  _icon_next = 0;
  _pixmap_next = 0;
}

QAbstractButton *
Image_control::get_button_previous() const
{
  return _button_previous;
}

QIcon *
Image_control::get_icon_previous() const
{
  return _icon_previous;
}

QPixmap *
Image_control::get_pixmap_previous() const
{
  return _pixmap_previous;
}

QAbstractButton *
Image_control::get_button_reset() const
{
  return _button_reset;
}

QIcon *
Image_control::get_icon_reset() const
{
  return _icon_reset;
}

QPixmap *
Image_control::get_pixmap_reset() const
{
  return _pixmap_reset;
}

QAbstractButton *
Image_control::get_button_next() const
{
  return _button_next;
}

QIcon *
Image_control::get_icon_next() const
{
  return _icon_next;
}

QPixmap *
Image_control::get_pixmap_next() const
{
  return _pixmap_next;
}

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
