/*
 * art-frame -- an artful sands image emulation
 *
 * Copyright (C) 2019 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/art-frame>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef SIMULATION_CONTROL_HH
#define SIMULATION_CONTROL_HH

#include <QtWidgets/QDial>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QGroupBox>
#include <iconfig.hh>

class Simulation_control : public QGroupBox
{
  Q_OBJECT
public:
  explicit Simulation_control(QWidget *parent, const IConfig *config);
  virtual ~Simulation_control();
  QPushButton *get_button_mode() const;
  QIcon *get_icon_pause() const;
  QPixmap *get_pixmap_pause() const;
  QIcon *get_icon_resume() const;
  QPixmap *get_pixmap_resume() const;
  QDial *get_dial_gravity() const;
private:
  QPushButton *_button_mode;
  QIcon *_icon_pause;
  QPixmap *_pixmap_pause;
  QIcon *_icon_resume;
  QPixmap *_pixmap_resume;
  QDial *_dial_gravity;
  QWidget *create_gravity_control(QDial **dial_gravity, const IConfig *config);
};

#endif /* SIMULATION_CONTROL_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
