/*
 * art-frame -- an artful sands image emulation
 *
 * Copyright (C) 2019 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/art-frame>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef TITLED_BUTTON_HH
#define TITLED_BUTTON_HH

#include <QtGui/QImage>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QToolButton>
#include <iconfig.hh>

class Titled_button : public QToolButton
{
public:
  Titled_button(QWidget *parent,
                const char *tool_tip_text,
                const char *title = NULL,
                const char *image_path = NULL);
  void set_title(const QString &title);
  bool set_image(const QImage &image);
  virtual ~Titled_button();
private:
  static const int BUTTON_WIDTH;
  static const int BUTTON_HEIGHT;
  static const int ICON_WIDTH;
  static const int ICON_HEIGHT;
  static const int TITLE_FONT_SIZE;
  QLabel *_label;
  QPixmap *_pixmap;
  QHBoxLayout *_layout;
};

#endif /* TITLED_BUTTON_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
